apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: "ratings"
  namespace: "vm"
spec:
  metadata:
    labels:
      app: "ratings"
  template:
    serviceAccount: "vm-sa"
    network: "vm-network"