apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-istiod-1-16-0
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  destination:
    namespace: istio-system
    name: gke_solo-test-236622_us-west1-c_daniel-cluster
  project: default
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.16.0
    helm:
      values: |
        revision: 1-16-0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: '*'
    kind: '*'
    managedFieldsManagers:
    - argocd-application-controller