apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  destination:
    namespace: cert-manager
    name: in-cluster
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.10.0
    helm:
      parameters:
      - name: installCRDs
        value: "true"
      - name: prometheus.enabled
        value: "false"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true