apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-istiod-1-16-0
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  destination:
    namespace: istio-system
    name: in-cluster
  project: default
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.16.0
    helm:
      values: |
        revision: 1-16-0
        meshConfig:
          defaultConfig:
            proxyMetadata:
              ISTIO_META_ENABLE_HBONE: "true"
        pilot:
          env:
            PILOT_ENABLE_INBOUND_PASSTHROUGH: "false"
            PILOT_ENABLE_HBONE: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: '*'
    kind: '*'
    managedFieldsManagers:
    - argocd-application-controller